version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bch-frontend
    ports:
      - "8080:80"
    networks:
      - bch-network
    restart: unless-stopped

  backend:
    build:
      context: /home/juwon/bch-backend
      dockerfile: Dockerfile
    container_name: bch-backend
    ports:
      - "8000:8000"
    env_file:
      - /home/juwon/bch-backend/.env
    networks:
      - bch-network
    restart: unless-stopped
    extra_hosts:
      - "btc-db.cfqsac0ma55f.us-east-2.rds.amazonaws.com:3.22.161.15"

networks:
  bch-network:
    driver: bridge